; Generated by AutoGUI 1.3.1a
#NoEnv
#Warn
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Default = Auth Code

Gui New, +Resize
Gui Color, 0x00FF00
Gui Add, Edit, vAuth1 x10 y10 w120 h20, Auth Code
Gui Add, Button, hWndhButton1 gButton1 x10 y160 w120 h20, &SUBMIT
Gui Add, Edit, vAuth2 x10 y35 w120 h20, Auth Code
Gui Add, Edit, vAuth3 x10 y60 w120 h20, Auth Code
Gui Add, Edit, vAuth4 x10 y85 w120 h20, Auth Code
Gui Add, Edit, vAuth5 x10 y110 w120 h20, Auth Code
Gui Add, Edit, vAuth6 x10 y135 w120 h20, Auth Code
Gui Add, Text, x140 y10 w210 h20 +0x200, #1. Paste auth codes in to the open slots
Gui Add, Text, x140 y30 w210 h20 +0x200, #2. Make sure EradicationX Client is open
Gui Add, Text, x140 y50 w210 h20 +0x200, #3. Make sure you are logged in
Gui Add, Text, x140 y70 w210 h20 +0x200, #4. Press Submit
Gui Show, w363 h186
OnMessage(0x201, "WM_LBUTTONDOWN")
Return

Button1:
Gui, Submit, NoHide
WinActivate, EradicationX
Sleep 500 
Send {Space}
Send {BS Down}
ToolTip, Clearing Chat - Holding Backspace For 6 More Seconds.
SetTimer, RemoveToolTip, 1000
Sleep 1000
ToolTip, Clearing Chat - Holding Backspace For 5 More Seconds.
SetTimer, RemoveToolTip, 1000
Sleep 1000
ToolTip, Clearing Chat - Holding Backspace For 4 More Seconds.
SetTimer, RemoveToolTip, 1000
Sleep 1000
ToolTip, Clearing Chat - Holding Backspace For 3 More Seconds.
SetTimer, RemoveToolTip, 1000
Sleep 1000
ToolTip, Clearing Chat - Holding Backspace For 2 More Seconds.
SetTimer, RemoveToolTip, 1000
Sleep 1000
ToolTip, Clearing Chat - Holding Backspace For 1 More Second.
SetTimer, RemoveToolTip, 1000
Sleep 1000
Send {BS Up}

if Default <> %Auth1%
{
ToolTip, Inputing The 1st Auth Code.
SetTimer, RemoveToolTip, 2000
Sleep 500
Send ::redeem %Auth1% {Enter}
Sleep 1500
Send {Space}
Send {BS}
}
else
{
goto code2
}
code2:
if Default <> %Auth2%
{
ToolTip, Inputing The 2nd Auth Code.
SetTimer, RemoveToolTip, 1000
Sleep 500
Send ::redeem %Auth2% {Enter}
Sleep 1500
Send {Space}
Send {BS}
}
else
{
goto code3
}
code3:
if Default <> %Auth3%
{
ToolTip, Inputing The 3rd Auth Code.
SetTimer, RemoveToolTip, 1000
Sleep 500
Send ::redeem %Auth3% {Enter}
Sleep 1500
Send {Space}
Send {BS}
}
else
{
goto code4
}
code4:
if Default <> %Auth4%
{
ToolTip, Inputing The 4th Auth Code.
SetTimer, RemoveToolTip, 1000
Sleep 500
Send ::redeem %Auth4% {Enter}
Sleep 1500
Send {Space}
Send {BS}
}
else
{
goto code5
}
code5:
if Default <> %Auth5%
{
ToolTip, Inputing The 5th Auth Code.
SetTimer, RemoveToolTip, 1000
Sleep 500
Send ::redeem %Auth5% {Enter}
Sleep 1500
Send {Space}
Send {BS}
}
else
{
goto code6
}
code6:
if Default <> %Auth6%
{
ToolTip, Inputing The 6th Auth Code.
SetTimer, RemoveToolTip, 1000
Sleep 500
Send ::redeem %Auth6% {Enter}
Sleep 1500
Send {Space}
Send {BS}
return
}
else
{
return
}

WM_LBUTTONDOWN(wParam, lParam) 
{ 
    if (A_GuiControl = "Auth1") { 
     GuiControl,, Auth1, 
    } 
    if (A_GuiControl = "Auth2") { 
     GuiControl,, Auth2, 
    } 
    if (A_GuiControl = "Auth3") { 
     GuiControl,, Auth3, 
    } 
    if (A_GuiControl = "Auth4") { 
     GuiControl,, Auth4, 
    } 
    if (A_GuiControl = "Auth5") { 
     GuiControl,, Auth5, 
    } 
    if (A_GuiControl = "Auth6") { 
     GuiControl,, Auth6, 
    } 
} 

GuiEscape:
GuiClose:
    ExitApp

RemoveToolTip:
SetTimer, RemoveToolTip, Off
ToolTip
return
; Do not edit above this line